export async function onRequest(context) {
  const response = await context.next();
  const url = new URL(context.request.url);
  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('text/html')) return response;
  let html = await response.text();

  // Make Coaches a deliberate red callout everywhere it appears in navigation.
  html = html.replace('</head>', `<style id="coachesNavHighlight">.links a[href="/coaches.html"],.mobile-menu a[href="/coaches.html"]{color:#e32636!important}.links a[href="/coaches.html"]:hover,.mobile-menu a[href="/coaches.html"]:hover{color:#ff5361!important}</style>\n</head>`);

  if (url.pathname === '/' || url.pathname === '/index.html') {
    const tickerMarkup = `
<div id="recentScoresShell" class="scores-ticker-shell" hidden><div class="wrap scores-ticker"><div class="scores-ticker-label">Recent Scores</div><div id="recentScoresTrack" class="scores-ticker-track" aria-label="Recent scores"></div></div></div>
<div id="championCelebration" class="champion-celebration" hidden aria-hidden="true"><div id="championConfetti" class="champion-confetti" aria-hidden="true"></div><div class="champion-card" role="dialog" aria-modal="true" aria-labelledby="championTitle"><button id="championClose" class="champion-close" type="button" aria-label="Close celebration">×</button><div class="champion-kicker">Kanab Sports</div><div class="champion-trophy">🏆</div><h2 id="championTitle">STATE CHAMPIONS!</h2><p id="championMessage"></p><button id="championDone" class="champion-done" type="button">LET'S GO!</button></div></div>`;
    const styles=`<style id="recentScoresStyles">.scores-ticker-shell{background:#fff;border-top:1px solid #e5e5e2;border-bottom:1px solid #e5e5e2;overflow:hidden}.scores-ticker{display:flex;align-items:stretch;overflow:hidden;min-height:50px}.scores-ticker-label{flex:0 0 auto;background:#0b0c0f;color:#fff;padding:0 20px;display:flex;align-items:center;font-size:10px;font-weight:950;letter-spacing:1.35px;text-transform:uppercase;z-index:2;white-space:nowrap}.scores-ticker-track{display:flex;flex:1;min-width:0;overflow-x:auto;scrollbar-width:none}.scores-ticker-track::-webkit-scrollbar{display:none}.score-tick{flex:0 0 auto;display:flex;align-items:center;gap:9px;padding:0 20px;border-right:1px solid #eee;white-space:nowrap;font-size:13px;color:#444}.score-sport{font-size:10px;font-weight:950;letter-spacing:.8px;text-transform:uppercase;color:#777}.score-team{font-weight:850;color:#16171a}.score-result{font-weight:950;color:#e32636}.score-final{font-size:10px;font-weight:900;color:#8a8c92;text-transform:uppercase}.champion-celebration{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;background:rgba(6,7,9,.76);backdrop-filter:blur(7px);padding:18px}.champion-celebration[hidden]{display:none}.champion-card{position:relative;z-index:2;width:min(520px,100%);background:#0b0c0f;color:#fff;border:1px solid #333640;border-radius:24px;padding:34px 26px 28px;text-align:center;box-shadow:0 30px 100px rgba(0,0,0,.5)}.champion-close{position:absolute;right:14px;top:10px;border:0;background:transparent;color:#aeb1b8;font-size:32px;cursor:pointer}.champion-kicker{color:#e32636;font-size:11px;font-weight:950;letter-spacing:2px;text-transform:uppercase}.champion-trophy{font-size:58px;margin:16px 0 10px}.champion-card h2{font-size:clamp(42px,10vw,72px);line-height:.88;letter-spacing:-2.5px;margin:0;text-transform:uppercase;font-weight:950}.champion-card p{font-size:18px;line-height:1.45;color:#d1d3d8;margin:20px auto 0;max-width:410px}.champion-done{margin-top:24px;border:0;border-radius:11px;background:#e32636;color:#fff;padding:14px 22px;font-size:12px;font-weight:950}.champion-confetti{position:fixed;inset:0;z-index:1;overflow:hidden;pointer-events:none}.confetti-piece{position:absolute;top:-24px;width:10px;height:18px;border-radius:2px;opacity:.95;animation:championFall linear forwards}@keyframes championFall{to{transform:translate3d(var(--drift),110vh,0) rotate(var(--spin))}}@media(max-width:620px){.scores-ticker-label{padding:0 13px;font-size:9px}.score-tick{padding:0 15px;font-size:12px}.champion-card{padding:30px 18px 24px}}</style>`;
    const script=`<script id="recentScoresScript">(function(){const shell=document.getElementById('recentScoresShell'),track=document.getElementById('recentScoresTrack'),celebration=document.getElementById('championCelebration'),msg=document.getElementById('championMessage'),confetti=document.getElementById('championConfetti');if(!shell||!track)return;const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));const pd=v=>{const d=new Date(v+'T12:00:00');return isNaN(d)?null:d};function show(c){if(!c)return;const score=Number.isFinite(Number(c.teamScore))&&Number.isFinite(Number(c.opponentScore))?' '+c.teamScore+'–'+c.opponentScore:'';msg.textContent=(c.team||'Kanab')+' are your '+(c.sport?c.sport+' ':'')+'state champions!'+(c.opponent?' '+(c.team||'Kanab')+' defeated '+c.opponent+score+'.':'');celebration.hidden=false;document.body.style.overflow='hidden';confetti.innerHTML='';const colors=['#e32636','#fff','#f1b63b','#111318'];for(let i=0;i<120;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'vw';p.style.background=colors[i%4];p.style.animationDuration=2.8+Math.random()*3.2+'s';p.style.animationDelay=Math.random()*1.4+'s';p.style.setProperty('--drift',-100+Math.random()*200+'px');p.style.setProperty('--spin',360+Math.random()*1080+'deg');confetti.appendChild(p)}}function close(){celebration.hidden=true;document.body.style.overflow='';confetti.innerHTML=''}document.getElementById('championClose')?.addEventListener('click',close);document.getElementById('championDone')?.addEventListener('click',close);const demo=new URLSearchParams(location.search).get('celebration')==='demo';if(demo)show({team:'Cowgirls',sport:'Soccer',opponent:'Beaver',teamScore:7,opponentScore:3});fetch('/api/scores',{cache:'no-store'}).then(r=>r.json()).then(data=>{if(data.celebration&&!demo)show(data.celebration);const scores=Array.isArray(data.scores)?data.scores:[];if(!scores.length)return;const markup=scores.slice(0,12).map(s=>{const d=pd(s.date),dl=d?d.toLocaleDateString('en-US',{month:'short',day:'numeric'}):'';return '<div class="score-tick"><span class="score-sport">'+esc(s.sport)+'</span><span class="score-team">'+esc(s.team)+'</span><span class="score-result">'+esc(s.teamScore)+' — '+esc(s.opponentScore)+'</span><span class="score-team">'+esc(s.opponent)+'</span><span class="score-final">Final'+(dl?' · '+dl:'')+'</span></div>'}).join('');track.innerHTML=markup+markup;shell.hidden=false}).catch(()=>{});
// Approved coach events feed directly into Happening Now.
fetch('/api/events',{cache:'no-store'}).then(r=>r.json()).then(data=>{const events=Array.isArray(data.events)?data.events:[];if(!events.length)return;const heading=[...document.querySelectorAll('h2')].find(h=>/happening now/i.test(h.textContent));const section=heading?.closest('section');const list=section?.querySelector('.live-list');if(!list)return;events.forEach(e=>{if(document.querySelector('[data-coach-event="'+CSS.escape(String(e.id))+'"]'))return;const item=document.createElement(e.link?'a':'div');item.className='live-item';item.dataset.coachEvent=e.id;if(e.link){item.href=e.link;item.target='_blank';item.rel='noopener';item.style.textDecoration='none';item.style.color='inherit'}const d=e.date?new Date(e.date+'T12:00:00'):null;const when=d&&!isNaN(d)?d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'}):'Upcoming';item.innerHTML='<div class="when">'+esc(when+(e.sport?' · '+e.sport:''))+'</div><h3>'+esc(e.name)+'</h3><p>'+esc(e.details||e.meta||e.team||'Community sports event')+'</p>';list.prepend(item)})}).catch(()=>{});})();</script>`;
    if(!html.includes('id="recentScoresShell"')){html=html.replace('</head>',styles+'\n</head>');html=html.replace('<section class="section" id="registration">',tickerMarkup+'\n<section class="section" id="registration">');html=html.replace('</body>',script+'\n</body>')}
  }

  if (url.pathname === '/coaches.html' || url.pathname === '/coaches') {
    const guard=`<script id="coachTurnstileGuard">(function(){const form=document.getElementById('coachForm'),button=document.getElementById('submitButton'),status=document.getElementById('coachStatus'),widget=document.querySelector('.cf-turnstile'),type=document.getElementById('type'),result=document.getElementById('result');if(!form||!button||!status||!widget)return;if(result&&!document.getElementById('championshipField')){const f=document.createElement('div');f.id='championshipField';f.className='field full';f.style.cssText='border:1px solid #343740;background:#15171b;border-radius:12px;padding:14px 16px';f.innerHTML='<label style="display:flex;align-items:center;gap:12px;color:#fff;font-size:13px;text-transform:none"><input id="championship" type="checkbox" name="championship" value="yes" style="width:20px;height:20px;accent-color:#e32636"><span><strong style="display:block;font-size:14px">🏆 State Championship Win</strong><small style="display:block;color:#9da0a7;font-size:12px;margin-top:3px;font-weight:500">Check this only for a final state championship victory. After approval, Kanab Sports celebrates it for 24 hours.</small></span></label>';result.closest('.field')?.insertAdjacentElement('afterend',f)}const cf=document.getElementById('championshipField'),cb=document.getElementById('championship');function sc(){const yes=(type?.value||'Score')==='Score';if(cf)cf.style.display=yes?'flex':'none';if(!yes&&cb)cb.checked=false}type?.addEventListener('change',sc);document.querySelectorAll('.action[data-type]').forEach(x=>x.addEventListener('click',()=>setTimeout(sc,0)));sc();const token=()=>form.querySelector('input[name="cf-turnstile-response"]')?.value;form.addEventListener('submit',e=>{if(token())return;e.preventDefault();e.stopImmediatePropagation();status.textContent='Waiting for verification…';button.disabled=false;try{window.turnstile?.reset(widget)}catch{}},true);form.addEventListener('reset',()=>setTimeout(()=>{if(cb)cb.checked=false;sc()},0));})();</script>`;if(!html.includes('id="coachTurnstileGuard"'))html=html.replace('</body>',guard+'\n</body>')
  }
  const headers=new Headers(response.headers);headers.delete('content-length');return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
