export async function onRequestPost(context) {
  const { request, env } = context;
  try {
    const form=await request.formData(), documentAction=String(form.get('action')||'').trim();
    if(documentAction==='request-verification')return requestCoachVerification(request,env,form);
    if(documentAction==='upload')return uploadCoachDocument(request,env,form);
    const token=form.get('cf-turnstile-response'), honeypot=String(form.get('website')||'').trim();
    if(honeypot)return json({success:true});
    if(!token)return json({success:false,error:'Please wait for verification to finish, then try again.'},400);
    if(!env.TURNSTILE_SECRET_KEY)return json({success:false,error:'Verification service is not configured. Please contact Kanab Sports.'},500);
    if(!env.RESEND_API_KEY)return json({success:false,error:'Email delivery is unavailable. Please try again.'},500);
    const vb=new URLSearchParams();vb.set('secret',env.TURNSTILE_SECRET_KEY);vb.set('response',token);const ip=request.headers.get('CF-Connecting-IP');if(ip)vb.set('remoteip',ip);
    const vr=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:vb});const verification=await vr.json();if(!verification.success)return json({success:false,error:'Human verification failed. Please refresh and try again.'},403);
    const clean=(v,m=1500)=>String(v||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,m);
    const type=clean(form.get('type'),100)||'General question',source=clean(form.get('source'),80)||'Contact form',name=clean(form.get('name'),120),email=clean(form.get('email'),180),team=clean(form.get('team'),180),sport=clean(form.get('sport'),120),date=clean(form.get('date'),80),opponent=clean(form.get('opponent'),180),result=clean(form.get('result'),180),link=clean(form.get('link'),600),message=clean(form.get('message'),3000),coachCode=clean(form.get('coach_code'),80).toUpperCase();
    const coachProtected=source==='Coaches'||(source==='Community'&&type==='Score');
    if(coachProtected){if(!env.COACH_ACCESS_CODE)return json({success:false,error:'Coach access is not configured yet. Please contact Kanab Sports.'},503);const expected=String(env.COACH_ACCESS_CODE).trim().toUpperCase();if(!coachCode||coachCode!==expected)return json({success:false,error:'Coach access code is incorrect.'},403)}
    const champ=source==='Coaches'&&type==='Score'&&String(form.get('championship')||'').toLowerCase()==='yes';const stored=champ?'[[STATE_CHAMPION]]\n'+message:message;
    if(!name||!email||!message||!email.includes('@'))return json({success:false,error:'Please complete your name, email, and message.'},400);
    const reviewable=(source==='Coaches'||source==='Community');
    let review=null;if(reviewable&&env.SPORTS_DB){await ensureSchema(env.SPORTS_DB);const id=crypto.randomUUID(),rt=randomToken(),hash=await sha256(rt),expires=new Date(Date.now()+7*86400000).toISOString();await env.SPORTS_DB.prepare(`INSERT INTO coach_submissions (id,source,type,name,email,team,sport,event_date,opponent,result,link,message,status,review_token_hash,review_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,datetime('now'))`).bind(id,source,type,name,email,team,sport,date,opponent,result,link,stored,hash,expires).run();review={id,token:rt}}
    const subjectPrefix=source==='Coaches'?'Coach submission':source==='Community'?'Community submission':'Kanab Sports';
    const subject=`${subjectPrefix} — ${type}${sport?' — '+sport:''}${champ?' — STATE CHAMPIONSHIP':''}`;
    const rows=[['Submission',type],['Source',source],['Submitted by',name],['Email',email],['Team / Organization',team],['Sport',sport],['Date',date],['Opponent / Event',opponent],['Score / Result',result],['State Championship',champ?'YES 🏆':''],['Link',link]].filter(([,v])=>v);
    const origin=new URL(request.url).origin,approve=review?`${origin}/review?token=${encodeURIComponent(review.token)}&action=approve`:'',reject=review?`${origin}/review?token=${encodeURIComponent(review.token)}&action=reject`:'',feature=review&&type==='Event'?`${origin}/review?token=${encodeURIComponent(review.token)}&action=feature`:'';
    const text=[...rows.map(([l,v])=>`${l}: ${v}`),'',message,review?`\nApprove & publish: ${approve}${feature?'\nFeature now: '+feature:''}\nDeny: ${reject}\n`:''].join('\n');
    const htmlRows=rows.map(([l,v])=>`<tr><td style="padding:6px 14px 6px 0;font-weight:700;vertical-align:top">${escapeHtml(l)}</td><td style="padding:6px 0;vertical-align:top">${escapeHtml(v)}</td></tr>`).join('');
    const correctionNote=type==='Correction'?'<div style="margin:12px 0;color:#777;font-size:12px">Approving a correction marks it reviewed; make any needed site edit separately.</div>':'';
    const buttons=review?`<div style="margin-top:24px;padding-top:22px;border-top:1px solid #e5e5e5"><div style="font-weight:700;margin-bottom:12px">What should Kanab Sports do with this submission?</div>${correctionNote}<a href="${escapeHtml(approve)}" style="display:inline-block;background:#16833a;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin:0 8px 8px 0">✓ Approve</a>${feature?`<a href="${escapeHtml(feature)}" style="display:inline-block;background:#e32636;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin:0 8px 8px 0">★ Feature Now</a>`:''}<a href="${escapeHtml(reject)}" style="display:inline-block;background:#222;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin-bottom:8px">Deny</a><div style="color:#777;font-size:12px;margin-top:10px">Review links expire in 7 days and can only be used once.</div></div>`:'';
    const html=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:680px"><h2 style="margin:0 0 18px">New ${escapeHtml(subjectPrefix)}</h2><table style="border-collapse:collapse;margin-bottom:22px">${htmlRows}</table><div style="padding:16px 18px;background:#f5f5f5;border-radius:10px;white-space:pre-wrap">${escapeHtml(message)}</div>${buttons}</div>`;
    const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'Kanab Sports <website@kanabsports.com>',to:['howdy@kanabsports.com'],reply_to:email,subject,text,html})});if(!rr.ok)return json({success:false,error:'We could not send your message. Please try again.'},502);return json({success:true,reviewReady:Boolean(review)});
  }catch(error){console.error('Contact form error',error);return json({success:false,error:'Something went wrong. Please try again.'},500)}
}
export function onRequestGet(){return json({success:false,error:'Method not allowed.'},405)}
async function ensureSchema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS coach_submissions (id TEXT PRIMARY KEY,source TEXT NOT NULL,type TEXT NOT NULL,name TEXT,email TEXT,team TEXT,sport TEXT,event_date TEXT,opponent TEXT,result TEXT,link TEXT,message TEXT,status TEXT NOT NULL DEFAULT 'pending',review_token_hash TEXT,review_expires_at TEXT,reviewed_at TEXT,published_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();try{await db.prepare(`ALTER TABLE coach_submissions ADD COLUMN featured INTEGER NOT NULL DEFAULT 0`).run()}catch{}await db.prepare(`CREATE TABLE IF NOT EXISTS coach_document_verifications (id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,email TEXT NOT NULL,name TEXT NOT NULL,sport TEXT NOT NULL,team TEXT NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS coach_documents (id TEXT PRIMARY KEY,verification_id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,sport TEXT NOT NULL,team TEXT NOT NULL,document_type TEXT NOT NULL,season TEXT NOT NULL,notes TEXT,filename TEXT NOT NULL,byte_size INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',review_token_hash TEXT,review_expires_at TEXT,is_test INTEGER NOT NULL DEFAULT 0,test_expires_at TEXT,reviewed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(24));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}

const MAX_PDF_BYTES=5*1024*1024,ADMIN_EMAIL='howdy@kanabsports.com';
async function requestCoachVerification(request,env,form){
  if(!env.SPORTS_DB||!env.RESEND_API_KEY||!env.TURNSTILE_SECRET_KEY)return json({success:false,error:'Coach document uploads are not configured yet.'},503);
  if(cleanField(form.get('website'),100))return json({success:true});
  const turnstile=cleanField(form.get('cf-turnstile-response'),3000);if(!turnstile)return json({success:false,error:'Please wait for verification to finish.'},400);
  if(!(await verifyCoachTurnstile(request,env.TURNSTILE_SECRET_KEY,turnstile)))return json({success:false,error:'Human verification failed. Please refresh and try again.'},403);
  const name=cleanField(form.get('name'),120),email=cleanField(form.get('email'),180).toLowerCase(),sport=cleanField(form.get('sport'),120),team=cleanField(form.get('team'),180);
  if(!name||!validEmail(email)||!sport||!team)return json({success:false,error:'Please complete your name, email, sport, and team.'},400);
  await ensureSchema(env.SPORTS_DB);await cleanupExpiredTests(env.SPORTS_DB);
  const id=crypto.randomUUID(),token=randomToken(),hash=await sha256(token),expires=new Date(Date.now()+30*60*1000).toISOString();
  await env.SPORTS_DB.prepare(`INSERT INTO coach_document_verifications (id,token_hash,email,name,sport,team,expires_at,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))`).bind(id,hash,email,name,sport,team,expires).run();
  const origin=new URL(request.url).origin,verifyUrl=`${origin}/coach-documents.html?token=${encodeURIComponent(token)}`,subject='Verify your email to upload a coach document';
  const text=`Hi ${name},\n\nOpen this secure link to upload a PDF roster, schedule, or combined document:\n${verifyUrl}\n\nThe link expires in 30 minutes. If you did not request it, you can ignore this email.`;
  const html=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:620px"><h2>Verify your coach email</h2><p>Hi ${escapeHtml(name)},</p><p>Use the button below to upload a PDF roster, schedule, or combined document.</p><p><a href="${escapeHtml(verifyUrl)}" style="display:inline-block;background:#e32636;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px">Verify email &amp; upload PDF</a></p><p style="color:#666;font-size:13px">This link expires in 30 minutes. If you did not request it, you can ignore this email.</p></div>`;
  const sent=await sendCoachEmail(env.RESEND_API_KEY,{from:'Kanab Sports <website@kanabsports.com>',to:[email],reply_to:ADMIN_EMAIL,subject,text,html},`coach-verify-${id}`);
  if(!sent){await env.SPORTS_DB.prepare(`DELETE FROM coach_document_verifications WHERE id=?`).bind(id).run();return json({success:false,error:'We could not send the verification email. Please try again.'},502)}
  return json({success:true,message:'Check your email for the secure upload link.'});
}
async function uploadCoachDocument(request,env,form){
  if(!env.SPORTS_DB||!env.RESEND_API_KEY)return json({success:false,error:'Coach document uploads are not configured yet.'},503);
  await ensureSchema(env.SPORTS_DB);await cleanupExpiredTests(env.SPORTS_DB);
  const token=cleanField(form.get('token'),200),row=await findCoachVerification(env.SPORTS_DB,token);if(!row)return json({success:false,error:'This verification link is invalid, expired, or already used.'},410);
  const documentType=cleanField(form.get('document_type'),80),season=cleanField(form.get('season'),100),notes=cleanField(form.get('notes'),1500),isTest=String(form.get('is_test')||'').toLowerCase()==='yes';
  if(!new Set(['Roster','Schedule','Roster and schedule']).has(documentType)||!season)return json({success:false,error:'Choose the document type and enter the season.'},400);
  const file=form.get('pdf');if(!file||typeof file.arrayBuffer!=='function'||!file.name)return json({success:false,error:'Choose a PDF to upload.'},400);
  if(file.size<5||file.size>MAX_PDF_BYTES)return json({success:false,error:'The PDF must be 5 MB or smaller.'},413);if(file.type&&file.type!=='application/pdf')return json({success:false,error:'Only PDF files are accepted.'},415);
  const bytes=new Uint8Array(await file.arrayBuffer());if(String.fromCharCode(...bytes.subarray(0,5))!=='%PDF-')return json({success:false,error:'That file does not appear to be a valid PDF.'},415);
  const reserved=await env.SPORTS_DB.prepare(`UPDATE coach_document_verifications SET used_at=datetime('now') WHERE id=? AND used_at IS NULL`).bind(row.id).run();if(!reserved.meta?.changes)return json({success:false,error:'This verification link has already been used.'},409);
  const id=crypto.randomUUID(),reviewToken=randomToken(),reviewHash=await sha256(reviewToken),reviewExpires=new Date(Date.now()+(isTest?5*60*1000:7*24*60*60*1000)).toISOString(),filename=safeCoachFilename(file.name);
  await env.SPORTS_DB.prepare(`INSERT INTO coach_documents (id,verification_id,name,email,sport,team,document_type,season,notes,filename,byte_size,status,review_token_hash,review_expires_at,is_test,test_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,?,?,datetime('now'))`).bind(id,row.id,row.name,row.email,row.sport,row.team,documentType,season,notes,filename,bytes.byteLength,reviewHash,reviewExpires,isTest?1:0,isTest?reviewExpires:null).run();
  const origin=new URL(request.url).origin,approve=`${origin}/review?token=${encodeURIComponent(reviewToken)}&action=approve`,reject=`${origin}/review?token=${encodeURIComponent(reviewToken)}&action=reject`,deleteTest=isTest?`${origin}/review?token=${encodeURIComponent(reviewToken)}&action=delete`:'',kind=documentType.toLowerCase(),recap=`Verified email — Coach ${row.name} uploaded ${article(kind)} ${kind} for ${season}.`,subject=`${isTest?'TEST — ':''}Verified coach document — ${row.name} — ${row.sport}`;
  const rows=[['Status','Email verified'],['Coach',row.name],['Email',row.email],['Sport',row.sport],['Team',row.team],['Document',documentType],['Season',season],['File',filename],['Test',isTest?'Yes — expires in 5 minutes':'No']],text=`${recap}\n\n${rows.map(([l,v])=>`${l}: ${v}`).join('\n')}${notes?`\n\nNotes: ${notes}`:''}\n\nApprove: ${approve}\nDeny: ${reject}${deleteTest?`\nDelete test: ${deleteTest}`:''}`,htmlRows=rows.map(([l,v])=>`<tr><td style="padding:6px 14px 6px 0;font-weight:700">${escapeHtml(l)}</td><td style="padding:6px 0">${escapeHtml(v)}</td></tr>`).join('');
  const html=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:680px"><h2>${escapeHtml(recap)}</h2><table style="border-collapse:collapse;margin:18px 0">${htmlRows}</table>${notes?`<div style="padding:14px;background:#f5f5f5;border-radius:8px"><strong>Notes</strong><br>${escapeHtml(notes)}</div>`:''}<div style="margin-top:24px"><a href="${escapeHtml(approve)}" style="display:block;background:#16833a;color:#fff;text-decoration:none;text-align:center;font-size:20px;font-weight:800;padding:18px 24px;border-radius:10px">✓ Approve &amp; publish to preview</a><div style="margin-top:28px;padding-top:18px;border-top:1px solid #e5e5e5;text-align:center"><a href="${escapeHtml(reject)}" style="display:inline-block;color:#9d2028;text-decoration:none;font-size:13px;font-weight:700;padding:10px 16px;border:1px solid #d8a8ab;border-radius:8px">Deny submission</a><div style="color:#777;font-size:11px;margin-top:7px">Deny requires a second confirmation.</div></div>${deleteTest?`<a href="${escapeHtml(deleteTest)}" style="display:block;color:#a00;font-size:12px;font-weight:700;padding:12px;text-align:center">Delete test</a>`:''}</div><p style="color:#666;font-size:12px">The PDF is attached and remains private; it is never published automatically.</p></div>`;
  // Send the approval controls separately from the attachment. Some mailbox
  // filters quarantine PDF messages; the reviewer should still receive the
  // actionable recap even when the document message is delayed or filtered.
  const reviewSent=await sendCoachEmail(env.RESEND_API_KEY,{from:'Kanab Sports <website@kanabsports.com>',to:[ADMIN_EMAIL],reply_to:row.email,subject,text,html},`coach-document-review-${id}`);
  if(!reviewSent){await env.SPORTS_DB.batch([env.SPORTS_DB.prepare(`DELETE FROM coach_documents WHERE id=?`).bind(id),env.SPORTS_DB.prepare(`UPDATE coach_document_verifications SET used_at=NULL WHERE id=?`).bind(row.id)]);return json({success:false,error:'The approval email could not be delivered. Please try again.'},502)}
  const attachmentSubject=`${isTest?'TEST — ':''}Private PDF — ${row.name} — ${row.sport}`;
  const attachmentText=`Private coach PDF attached.\n\nCoach: ${row.name}\nSport: ${row.sport}\nTeam: ${row.team}\nDocument: ${documentType}\nSeason: ${season}\nFile: ${filename}\n\nApprove: ${approve}\nDeny: ${reject}${deleteTest?`\nDelete test: ${deleteTest}`:''}`;
  const attachmentHtml=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:620px"><h2>Private coach PDF attached</h2><p>Review the attached document, then approve it below.</p><table style="border-collapse:collapse;margin:18px 0">${htmlRows}</table><div style="margin:24px 0"><a href="${escapeHtml(approve)}" style="display:block;background:#16833a;color:#fff;text-decoration:none;text-align:center;font-size:20px;font-weight:800;padding:18px 24px;border-radius:10px">✓ Approve &amp; publish to preview</a><div style="margin-top:28px;padding-top:18px;border-top:1px solid #e5e5e5;text-align:center"><a href="${escapeHtml(reject)}" style="display:inline-block;color:#9d2028;text-decoration:none;font-size:13px;font-weight:700;padding:10px 16px;border:1px solid #d8a8ab;border-radius:8px">Deny submission</a><div style="color:#777;font-size:11px;margin-top:7px">Deny requires a second confirmation.</div></div>${deleteTest?`<a href="${escapeHtml(deleteTest)}" style="display:block;color:#a00;font-size:12px;font-weight:700;padding:12px;text-align:center">Delete test</a>`:''}</div><p style="color:#666;font-size:12px">Keep this PDF private. A separate approval-only email is also sent as a backup.</p></div>`;
  const attachmentSent=await sendCoachEmail(env.RESEND_API_KEY,{from:'Kanab Sports <website@kanabsports.com>',to:[ADMIN_EMAIL],reply_to:row.email,subject:attachmentSubject,text:attachmentText,html:attachmentHtml,attachments:[{filename,content:toBase64(bytes)}]},`coach-document-attachment-${id}`);
  const receiptSubject=`PDF received — ${documentType} — ${row.sport}`,receiptText=`Hi ${row.name},\n\nKanab Sports received your ${kind} for ${season}. It was sent privately to ${ADMIN_EMAIL} for review.${isTest?' This test review expires in 5 minutes.':''}\n\nDocument: ${documentType}\nSport: ${row.sport}\nTeam: ${row.team}\nSeason: ${season}\nFile: ${filename}\n\nNo further action is needed unless Kanab Sports contacts you.`,receiptHtml=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:620px"><h2>Your PDF was received</h2><p>Hi ${escapeHtml(row.name)},</p><p>Kanab Sports received your ${escapeHtml(kind)} for ${escapeHtml(season)}. It was sent privately to <strong>${escapeHtml(ADMIN_EMAIL)}</strong> for review.${isTest?' This test review expires in 5 minutes.':''}</p><table style="border-collapse:collapse;margin:18px 0"><tr><td style="padding:6px 14px 6px 0;font-weight:700">Document</td><td>${escapeHtml(documentType)}</td></tr><tr><td style="padding:6px 14px 6px 0;font-weight:700">Sport</td><td>${escapeHtml(row.sport)}</td></tr><tr><td style="padding:6px 14px 6px 0;font-weight:700">Team</td><td>${escapeHtml(row.team)}</td></tr><tr><td style="padding:6px 14px 6px 0;font-weight:700">Season</td><td>${escapeHtml(season)}</td></tr><tr><td style="padding:6px 14px 6px 0;font-weight:700">File</td><td>${escapeHtml(filename)}</td></tr></table><p>No further action is needed unless Kanab Sports contacts you.</p></div>`;
  const receiptSent=await sendCoachEmail(env.RESEND_API_KEY,{from:'Kanab Sports <website@kanabsports.com>',to:[row.email],reply_to:ADMIN_EMAIL,subject:receiptSubject,text:receiptText,html:receiptHtml},`coach-document-receipt-${id}`);
  const baseMessage=isTest?`Test approval sent to ${ADMIN_EMAIL}. Its review link expires in 5 minutes.`:`Approval sent to ${ADMIN_EMAIL}.`;
  const attachmentMessage=attachmentSent?'The PDF was sent in a separate private email.':'The approval was sent, but the separate PDF email was not accepted; Kanab Sports will contact you if the file is needed again.';
  return json({success:true,message:`${baseMessage} ${attachmentMessage} ${receiptSent?'A confirmation was emailed to you.':'Your confirmation email could not be sent.'}`});
}
async function findCoachVerification(db,token){if(!token)return null;const hash=await sha256(token);return db.prepare(`SELECT id,email,name,sport,team FROM coach_document_verifications WHERE token_hash=? AND used_at IS NULL AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(hash).first()}
async function verifyCoachTurnstile(request,secret,response){const body=new URLSearchParams({secret,response}),ip=request.headers.get('CF-Connecting-IP');if(ip)body.set('remoteip',ip);const result=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!result.ok)return false;const data=await result.json();return Boolean(data.success)}
async function sendCoachEmail(apiKey,payload,idempotencyKey){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','Idempotency-Key':idempotencyKey},body:JSON.stringify(payload)});if(!response.ok)console.error(JSON.stringify({message:'coach document email failed',status:response.status}));return response.ok}
async function cleanupExpiredTests(db){await db.prepare(`DELETE FROM coach_documents WHERE is_test=1 AND test_expires_at IS NOT NULL AND datetime(test_expires_at)<=datetime('now')`).run();await db.prepare(`DELETE FROM coach_document_verifications WHERE used_at IS NULL AND datetime(expires_at)<=datetime('now','-1 day')`).run()}
function toBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
function safeCoachFilename(value){const cleaned=String(value).replace(/[^a-zA-Z0-9._ -]/g,'_').replace(/\s+/g,' ').trim().slice(0,120);return /\.pdf$/i.test(cleaned)?cleaned:`${cleaned||'coach-document'}.pdf`}
function article(value){return /^[aeiou]/i.test(value)?'an':'a'}
function cleanField(value,max=500){return String(value||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,max)}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
