export async function onRequestPost(context) {
  const { request, env } = context;
  try {
    const form=await request.formData(), token=form.get('cf-turnstile-response'), honeypot=String(form.get('website')||'').trim();
    if(honeypot)return json({success:true});
    if(!token)return json({success:false,error:'Please wait for verification to finish, then try again.'},400);
    if(!env.TURNSTILE_SECRET_KEY)return json({success:false,error:'Verification service is not configured. Please contact Kanab Sports.'},500);
    if(!env.RESEND_API_KEY)return json({success:false,error:'Email delivery is unavailable. Please try again.'},500);
    const vb=new URLSearchParams();vb.set('secret',env.TURNSTILE_SECRET_KEY);vb.set('response',token);const ip=request.headers.get('CF-Connecting-IP');if(ip)vb.set('remoteip',ip);
    const vr=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:vb});const verification=await vr.json();if(!verification.success)return json({success:false,error:'Human verification failed. Please refresh and try again.'},403);
    const clean=(v,m=1500)=>String(v||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,m);
    const type=clean(form.get('type'),100)||'General question',source=clean(form.get('source'),80)||'Contact form',name=clean(form.get('name'),120),email=clean(form.get('email'),180),team=clean(form.get('team'),180),sport=clean(form.get('sport'),120),date=clean(form.get('date'),80),opponent=clean(form.get('opponent'),180),result=clean(form.get('result'),180),link=clean(form.get('link'),600),message=clean(form.get('message'),3000),coachCode=clean(form.get('coach_code'),80).toUpperCase();
    const coachProtected=source==='Coaches'||(source==='Community'&&type==='Score');
    if(coachProtected){if(!env.COACH_ACCESS_CODE)return json({success:false,error:'Coach access is not configured yet. Please contact Kanab Sports.'},503);const expected=String(env.COACH_ACCESS_CODE).trim().toUpperCase();if(!coachCode||coachCode!==expected)return json({success:false,error:'Coach access code is incorrect.'},403)}
    const champ=source==='Coaches'&&type==='Score'&&String(form.get('championship')||'').toLowerCase()==='yes';const stored=champ?'[[STATE_CHAMPION]]\n'+message:message;
    if(!name||!email||!message||!email.includes('@'))return json({success:false,error:'Please complete your name, email, and message.'},400);
    const reviewable=(source==='Coaches'||source==='Community');
    let review=null;if(reviewable&&env.SPORTS_DB){await ensureSchema(env.SPORTS_DB);const id=crypto.randomUUID(),rt=randomToken(),hash=await sha256(rt),expires=new Date(Date.now()+7*86400000).toISOString();await env.SPORTS_DB.prepare(`INSERT INTO coach_submissions (id,source,type,name,email,team,sport,event_date,opponent,result,link,message,status,review_token_hash,review_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,datetime('now'))`).bind(id,source,type,name,email,team,sport,date,opponent,result,link,stored,hash,expires).run();review={id,token:rt}}
    const subjectPrefix=source==='Coaches'?'Coach submission':source==='Community'?'Community submission':'Kanab Sports';
    const subject=`${subjectPrefix} — ${type}${sport?' — '+sport:''}${champ?' — STATE CHAMPIONSHIP':''}`;
    const rows=[['Submission',type],['Source',source],['Submitted by',name],['Email',email],['Team / Organization',team],['Sport',sport],['Date',date],['Opponent / Event',opponent],['Score / Result',result],['State Championship',champ?'YES 🏆':''],['Link',link]].filter(([,v])=>v);
    const origin=new URL(request.url).origin,approve=review?`${origin}/review?token=${encodeURIComponent(review.token)}&action=approve`:'',reject=review?`${origin}/review?token=${encodeURIComponent(review.token)}&action=reject`:'',feature=review&&type==='Event'?`${origin}/review?token=${encodeURIComponent(review.token)}&action=feature`:'';
    const text=[...rows.map(([l,v])=>`${l}: ${v}`),'',message,review?`\nApprove & publish: ${approve}${feature?'\nFeature now: '+feature:''}\nDeny: ${reject}\n`:''].join('\n');
    const htmlRows=rows.map(([l,v])=>`<tr><td style="padding:6px 14px 6px 0;font-weight:700;vertical-align:top">${escapeHtml(l)}</td><td style="padding:6px 0;vertical-align:top">${escapeHtml(v)}</td></tr>`).join('');
    const correctionNote=type==='Correction'?'<div style="margin:12px 0;color:#777;font-size:12px">Approving a correction marks it reviewed; make any needed site edit separately.</div>':'';
    const buttons=review?`<div style="margin-top:24px;padding-top:22px;border-top:1px solid #e5e5e5"><div style="font-weight:700;margin-bottom:12px">What should Kanab Sports do with this submission?</div>${correctionNote}<a href="${escapeHtml(approve)}" style="display:inline-block;background:#16833a;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin:0 8px 8px 0">✓ Approve</a>${feature?`<a href="${escapeHtml(feature)}" style="display:inline-block;background:#e32636;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin:0 8px 8px 0">★ Feature Now</a>`:''}<a href="${escapeHtml(reject)}" style="display:inline-block;background:#222;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;margin-bottom:8px">Deny</a><div style="color:#777;font-size:12px;margin-top:10px">Review links expire in 7 days and can only be used once.</div></div>`:'';
    const html=`<div style="font-family:Arial,sans-serif;line-height:1.55;color:#111;max-width:680px"><h2 style="margin:0 0 18px">New ${escapeHtml(subjectPrefix)}</h2><table style="border-collapse:collapse;margin-bottom:22px">${htmlRows}</table><div style="padding:16px 18px;background:#f5f5f5;border-radius:10px;white-space:pre-wrap">${escapeHtml(message)}</div>${buttons}</div>`;
    const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:'Kanab Sports <website@kanabsports.com>',to:['howdy@kanabsports.com'],reply_to:email,subject,text,html})});if(!rr.ok)return json({success:false,error:'We could not send your message. Please try again.'},502);return json({success:true,reviewReady:Boolean(review)});
  }catch(error){console.error('Contact form error',error);return json({success:false,error:'Something went wrong. Please try again.'},500)}
}
export function onRequestGet(){return json({success:false,error:'Method not allowed.'},405)}
async function ensureSchema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS coach_submissions (id TEXT PRIMARY KEY,source TEXT NOT NULL,type TEXT NOT NULL,name TEXT,email TEXT,team TEXT,sport TEXT,event_date TEXT,opponent TEXT,result TEXT,link TEXT,message TEXT,status TEXT NOT NULL DEFAULT 'pending',review_token_hash TEXT,review_expires_at TEXT,reviewed_at TEXT,published_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();try{await db.prepare(`ALTER TABLE coach_submissions ADD COLUMN featured INTEGER NOT NULL DEFAULT 0`).run()}catch{} }
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(24));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
