export async function onRequestGet({request,env}){
  if(!env.SPORTS_DB)return page('The update service is unavailable.',false,503);
  const url=new URL(request.url),token=url.searchParams.get('token')||'',action=(url.searchParams.get('action')||'').toLowerCase();if(!token||!['approve','deny','undo'].includes(action))return page('This update link is invalid.',false,400);
  try{await schema(env.SPORTS_DB);const hash=await sha256(token),row=await env.SPORTS_DB.prepare(`SELECT id,title,status,review_expires_at FROM site_announcements WHERE review_token_hash=? LIMIT 1`).bind(hash).first();if(!row)return page('This link has already been used or is invalid.',false,404);if(action!=='undo'&&Date.parse(row.review_expires_at)<Date.now())return page('This review link has expired.',false,410);
    if(action==='approve'&&row.status==='pending'){await env.SPORTS_DB.prepare(`UPDATE site_announcements SET status='approved',reviewed_at=datetime('now'),published_at=datetime('now') WHERE id=?`).bind(row.id).run();return page(`${row.title} is live.`,true,200,'The ticker and Happening Now will update within about a minute.','/#registration','View the update')}
    if(action==='deny'&&row.status==='pending'){await env.SPORTS_DB.prepare(`UPDATE site_announcements SET status='rejected',reviewed_at=datetime('now'),review_token_hash=NULL WHERE id=?`).bind(row.id).run();return page('Update denied.',true,200,'Nothing was published.')}
    if(action==='undo'&&row.status==='approved'){await env.SPORTS_DB.prepare(`UPDATE site_announcements SET status='removed',removed_at=datetime('now'),review_token_hash=NULL WHERE id=?`).bind(row.id).run();return page('Update removed.',true,200,'It will disappear from the public site within about a minute.')}
    return page(`This update has already been ${row.status}.`,false,409);
  }catch(error){console.error('site update action error',error);return page('The action could not be completed.',false,500)}
}
async function schema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS site_announcements (id TEXT PRIMARY KEY,source TEXT NOT NULL,sender_email TEXT NOT NULL,message_id TEXT UNIQUE,original_subject TEXT,original_body TEXT,title TEXT NOT NULL,detail TEXT NOT NULL,sport TEXT,event_date TEXT,end_date TEXT,href TEXT,featured INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'pending',review_token_hash TEXT,review_expires_at TEXT,reviewed_at TEXT,published_at TEXT,removed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function sha256(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
function page(message,success,status,detail='You may close this page.',href='/',label='Back to Kanab Sports'){const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');return new Response(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kanab Sports Update</title><style>body{margin:0;background:#0b0c0f;color:#fff;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;display:grid;place-items:center;min-height:100vh}.card{width:min(560px,calc(100% - 32px));background:#15171b;border:1px solid #2d3036;border-radius:18px;padding:32px}.brand{font-size:24px;font-weight:950}.brand span{color:#e32636}h1{font-size:34px;line-height:1.05;margin:22px 0 10px}p{color:#b9bcc4}.button{display:block;margin-top:24px;background:${success?'#16833a':'#e32636'};color:#fff;text-align:center;text-decoration:none;font-size:18px;font-weight:900;padding:17px;border-radius:10px}</style></head><body><main class="card"><div class="brand">KANAB <span>SPORTS</span></div><h1>${esc(message)}</h1><p>${esc(detail)}</p><a class="button" href="${esc(href)}">${esc(label)}</a></main></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}
