const $=id=>document.getElementById(id),node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};let selected;
async function api(path,body){const multipart=body instanceof FormData;const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body&&!multipart?{'Content-Type':'application/json'}:{},body:body?(multipart?body:JSON.stringify(body)):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
const error=e=>$('status').textContent=e.message;
async function directory(){const d=await api('coach-family-directory');$('families').replaceChildren();for(const f of d.families){const b=node('button',f.student_name+' · '+f.parent_name+' · '+f.team);b.className='thread';b.onclick=()=>{selected=f;$('familyTitle').textContent=f.student_name+' · '+f.parent_name;$('audience').showModal();};$('families').append(b);}if(!d.families.length)$('families').append(node('p','No verified pilot families available.'));}
$('cancelFamily').onclick=()=>$('audience').close();$('messageFamily').onsubmit=async e=>{e.preventDefault();try{const d=await api('private-messages?role=coach',{action:'start_parent',audience:'parents',...selected});location.href='/messages/?role=coach&conversation='+encodeURIComponent(d.id);}catch(e){error(e);}};
async function schedules(){const d=await api('team-schedule-edit');$('schedules').replaceChildren();for(const t of d.teams){const section=document.createElement('section');section.append(node('h3',t.team_name));for(const event of t.events){const form=document.createElement('form');form.append(node('h4',event.title));const inputs={};for(const [key,label,type] of [['date','Date','date'],['time','Time','text'],['title','Event title','text'],['detail','Location / details','text'],['cancelled','Cancelled','checkbox']]){const input=document.createElement('input');input.type=type;input.disabled=!d.can_edit;if(type==='checkbox')input.checked=!!event[key];else input.value=event[key]||'';const l=node('label',label+' ');l.append(input);form.append(l,document.createElement('br'));inputs[key]=input;}const save=node('button','Save schedule change');save.disabled=!d.can_edit;form.append(save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{const body={team_code:t.team_code,event_id:event.id,revision:event.revision};for(const [k,v] of Object.entries(inputs))body[k]=v.type==='checkbox'?v.checked:v.value;const result=await api('team-schedule-edit',body);$('status').textContent=result.message;await schedules();}catch(e){error(e);save.disabled=false;}};section.append(form);}if(!t.events.length)section.append(node('p','Upload and approve a schedule first.'));$('schedules').append(section);}}
async function stats(){const d=await api('coach-stats');$('statsTeam').replaceChildren(...d.teams.map(t=>{const o=node('option',t.team_name);o.value=t.team_code;return o;}));$('files').replaceChildren(...d.files.map(f=>{const a=node('a',f.filename);a.href='/api/coach-stats?id='+encodeURIComponent(f.id);a.style.display='block';return a;}));if(!d.storageReady)$('files').append(node('p','Private PDF storage must be configured before uploading.'));}
$('stats').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const form=new FormData();form.set('team_code',$('statsTeam').value);form.set('pdf',$('pdf').files[0]);const d=await api('coach-stats',form);$('status').textContent=d.message;await stats();}catch(e){error(e);}finally{button.disabled=false;}};
await Promise.allSettled([directory().catch(error),schedules().catch(error),stats().catch(error)]);
