import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {accessSchema,hasMembership} from '../functions/_lib/parent-access.js';
import {ensureCoachCore} from '../functions/_lib/coach-auth.js';
import {onRequestGet as team} from '../functions/api/team-connection.js';
import {onRequest as access} from '../functions/api/guardian-access.js';
import {notifyTeam} from '../functions/_lib/web-push.js';
import {onRequest as push} from '../functions/api/push.js';
const sqlite=new DatabaseSync(':memory:');
const db={prepare(sql){const statement=sqlite.prepare(sql);let args=[];return {bind(...values){args=values;return this},async run(){return statement.run(...args)},async first(){return statement.get(...args)||null},async all(){return {results:statement.all(...args)}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=await Promise.all(statements.map(s=>s.run()));sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
await ensureCoachCore(db);await accessSchema(db);
sqlite.prepare("INSERT INTO coach_access_requests(id,name,email,organization,sport,role,status,team_code) VALUES('coach','Coach','coach@example.test','KHS','Soccer','Coach','approved','KS-TEST')").run();
const token='a'.repeat(64),hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))).toString('hex');
sqlite.prepare('INSERT INTO parent_sessions VALUES(?,?,?)').run(hash,'parent@example.test',Date.now()+60000);
const req=(path,body,signed=true)=>new Request('https://kanabsports.com'+path,{method:body?'POST':'GET',headers:{...(signed?{cookie:'__Host-ks_parent='+token}:{}),origin:'https://kanabsports.com','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const call=(fn,request)=>fn({request,env:{SPORTS_DB:db}});
assert.equal((await call(team,req('/api/team-connection?code=KS-TEST',null,false))).status,401);
assert.equal((await call(team,req('/api/team-connection?code=KS-TEST'))).status,403);
assert.equal((await call(access,req('/api/guardian-access',{action:'approve'}))).status,403);
assert.equal((await call(access,req('/api/guardian-access',{action:'request',team_code:'KS-TEST'}))).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-TEST'),false,'Request is not approval');
sqlite.prepare("INSERT INTO guardian_memberships VALUES('m',?,?,?,?,?,'approved','owner','school authorization',?)").run('parent@example.test','KS-TEST','student-1','Fall',Date.now()+60000,Date.now());
assert.equal((await call(team,req('/api/team-connection?code=KS-TEST'))).status,200);
assert.equal(await hasMembership(db,'other@example.test','KS-TEST'),false);
assert.equal(await hasMembership(db,'parent@example.test','KS-OTHER'),false);
sqlite.prepare("UPDATE guardian_memberships SET status='revoked'").run();
assert.equal((await call(team,req('/api/team-connection?code=KS-TEST'))).status,403);
assert.equal((await call(push,req('/api/push',{action:'subscribe',codes:['KS-TEST'],endpoint:'https://fcm.googleapis.com/test',token:'b'.repeat(64)}))).status,403);
sqlite.prepare("UPDATE guardian_memberships SET status='approved',expires=1").run();
assert.equal(await hasMembership(db,'parent@example.test','KS-TEST'),false);
console.log('PASS: shared code blocked; requests do not approve; parent cannot self-approve; correct membership allowed; wrong parent/team, revocation and expiry denied; unauthorized push blocked.');

const adminToken='owner-test-token',adminHash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(adminToken))).toString('hex');
sqlite.prepare("INSERT INTO admin_sessions(id,email,token_hash,expires_at) VALUES('owner','howdy@kanabsports.com',?,datetime('now','+1 hour'))").run(adminHash);
const ownerRequest=body=>new Request('https://kanabsports.com/api/guardian-access',{method:'POST',headers:{cookie:'ks_admin='+adminToken,origin:'https://kanabsports.com','content-type':'application/json'},body:JSON.stringify(body)});
const approved=await call(access,ownerRequest({action:'approve',email:'parent@example.test',team_code:'KS-TEST',student_ref:'student-2',season:'Fall 2026',evidence:'School-authorized test record',expires:new Date(Date.now()+86400000).toISOString(),confirmed:true}));
assert.equal(approved.status,200);const membership=await approved.json();
assert.equal(await hasMembership(db,'parent@example.test','KS-TEST'),true);
assert.equal((await call(push,req('/api/push',{action:'subscribe',codes:['KS-TEST'],endpoint:'https://fcm.googleapis.com/test',token:'b'.repeat(64)}))).status,200);
assert.equal((await call(access,ownerRequest({action:'revoke',id:membership.id}))).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-TEST'),false);
assert.deepEqual(await notifyTeam(db,'KS-TEST','test-no-delivery'),{accepted:0,failed:0});
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM guardian_access_audit').get().n,2);
console.log('PASS: owner approval and revocation audited; old push subscription skipped after revocation. No external messages sent.');
