import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {onRequestPost as inbound} from '../functions/api/twilio-inbound.js';
import {DatabaseSync} from 'node:sqlite';
import {schema,hash} from '../functions/_lib/pilot.js';
import {onRequest} from '../functions/api/peptalk.js';
const sqlite=new DatabaseSync(':memory:');
class S{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new S(this.sql,args)}async first(){return sqlite.prepare(this.sql).get(...this.args)||null}async all(){return {results:sqlite.prepare(this.sql).all(...this.args)}}async run(){return sqlite.prepare(this.sql).run(...this.args)}}
const db={prepare:s=>new S(s),batch:async ss=>{sqlite.exec('BEGIN');try{const rs=await Promise.all(ss.map(s=>s.run()));sqlite.exec('COMMIT');return rs}catch(e){sqlite.exec('ROLLBACK');throw e}}};
await schema(db);const token='b'.repeat(64),email=process.env.TEST_COACH_EMAIL;if(!email)throw Error('TEST_COACH_EMAIL required');
await db.prepare('INSERT INTO team_d_sessions VALUES(?,?,?)').bind(await hash(token),email,Date.now()+600000).run();
await db.prepare("INSERT INTO team_d_approvals(email,status) VALUES(?,'approved')").bind(email).run();
sqlite.exec("CREATE TABLE sms_enrollment(phone TEXT,team TEXT,status TEXT,step TEXT,match_status TEXT)");
for(const r of [['+15005550006','britt-soccer','consented','complete','matched'],['+15005550007','britt-soccer','opted_out','complete','matched'],['+15005550008','other-team','consented','complete','matched'],['+15005550009','britt-soccer','consented','guardian',null]])sqlite.prepare('INSERT INTO sms_enrollment VALUES(?,?,?,?,?)').run(...r);
const env={SPORTS_DB:db,TWILIO_AUTH_TOKEN:'test-only',TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_MESSAGING_SERVICE_SID:'MG'+'b'.repeat(32)};let calls=[];let fail=false;
const fields={Body:'HELP',From:'+15005550006',AccountSid:env.TWILIO_ACCOUNT_SID,MessagingServiceSid:env.TWILIO_MESSAGING_SERVICE_SID},webhook='https://kanabsports.com/api/twilio-inbound';
const signed=createHmac('sha1',env.TWILIO_AUTH_TOKEN).update(webhook+Object.keys(fields).sort().map(k=>k+fields[k]).join('')).digest('base64');
const incoming=sig=>inbound({env,request:new Request(webhook,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':sig},body:new URLSearchParams(fields)})});
assert.equal((await incoming('forged')).status,403);
assert.equal((await incoming(signed)).status,200);
delete env.TWILIO_ACCOUNT_SID;delete env.TWILIO_MESSAGING_SERVICE_SID;
assert.equal((await db.prepare("SELECT value FROM team_d_settings WHERE key='twilio_service_sid'").first()).value,fields.MessagingServiceSid);
globalThis.fetch=async(url,o)=>{calls.push({url,o});if(fail)throw Error('Timeout');const params=new URLSearchParams(o.body);return Response.json({sid:'SM'+'a'.repeat(32),status:params.get('Status')==='canceled'?'canceled':o.method==='GET'?'delivered':'scheduled'});};
const call=(body,{cookie=true,origin='https://kanabsports.com'}={})=>onRequest({env,request:new Request('https://kanabsports.com/api/peptalk',{method:body?'POST':'GET',headers:{...(cookie?{Cookie:'__Host-ks_team_d='+token}:{}),Origin:origin},body:body?JSON.stringify(body):undefined})});
assert.equal((await call(null,{cookie:false})).status,403);
assert.equal((await (await call()).json()).recipientCount,1);
const job={action:'schedule',id:crypto.randomUUID(),body:'Practice reminder',sendAt:Date.now()+3600000};
assert.equal((await call(job,{origin:'https://evil.invalid'})).status,403);
assert.equal((await call({...job,sendAt:Date.now()+60000})).status,400);
assert.equal((await call(job)).status,200);assert.equal(calls.length,1);
const payload=new URLSearchParams(calls[0].o.body);assert.equal(payload.get('To'),'+15005550006');assert.equal(payload.get('ScheduleType'),'fixed');assert.match(payload.get('MessagingServiceSid'),/^MG/);assert.match(payload.get('Body'),/Britt Roth/);
assert.equal((await call(job)).status,200);assert.equal(calls.length,1,'Repeated request must not schedule again');
await call({action:'cancel',id:job.id});assert.equal((await (await call()).json()).jobs[0].deliveryCounts[0].status,'canceled');
fail=true;const uncertain={...job,id:crypto.randomUUID()};await call(uncertain);const jobs=(await (await call()).json()).jobs;assert.equal(jobs.find(j=>j.id===uncertain.id).deliveryCounts[0].status,'unknown');const n=calls.length;await call(uncertain);assert.equal(calls.length,n,'Ambiguous network failure must never be retried automatically');
await db.prepare("UPDATE team_d_approvals SET status='denied'").run();assert.equal((await call({...job,id:crypto.randomUUID()})).status,403);
console.log('PASS: authorization, CSRF, recipient consent/team scope, schedule window, attribution, idempotency, cancellation, ambiguous failure');
