import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {ensureCoachCore} from '../functions/_lib/coach-auth.js';
import {accessSchema} from '../functions/_lib/parent-access.js';
import {authenticate} from '../functions/api/admin-dashboard.js';
import {onRequestPost as roster} from '../functions/api/guardian-import.js';
import {onRequestPost as account} from '../functions/api/coach-account.js';
import {onRequestPost as register} from '../functions/coach-register.js';
import {parseRosterCSV,validateRosterRows} from '../assets/guardian-import.mjs';
const sqlite=new DatabaseSync(':memory:');
const db={prepare(sql){const statement=sqlite.prepare(sql);let args=[];return {bind(...values){args=values;return this},async run(){return statement.run(...args)},async first(){return statement.get(...args)||null},async all(){return {results:statement.all(...args)}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=await Promise.all(statements.map(s=>s.run()));sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
await ensureCoachCore(db);await accessSchema(db);
sqlite.prepare("INSERT INTO coach_access_requests(id,name,email,organization,sport,role,status,team_code) VALUES('coach','Coach','coach@example.test','KHS','Soccer','Coach','approved','KS-TEST')").run();
const env={SPORTS_DB:db,RESEND_API_KEY:'mock',TURNSTILE_SECRET_KEY:'mock'};
const request=(path,body,cookie='')=>new Request('https://kanabsports.com'+path,{method:'POST',headers:{origin:'https://kanabsports.com','content-type':'application/json',cookie},body:JSON.stringify(body)});
const call=(fn,path,body,cookie)=>fn({request:request(path,body,cookie),env});
const expires=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
const csv=`\ufeffemail,student_ref,team_code,season,expires\r\nparent@example.test,"Student, One",KS-TEST,Fall,${expires}`;
const rows=validateRosterRows(parseRosterCSV(csv));assert.equal(rows[0].student_ref,'Student, One');
assert.throws(()=>parseRosterCSV(csv.replace('student_ref','DOB')));
assert.throws(()=>validateRosterRows([...rows,...rows]));
await authenticate(request('/api/guardian-import',{}),db);
const hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('owner-token'))).toString('hex');
sqlite.prepare("INSERT INTO admin_sessions(id,email,token_hash,expires_at) VALUES('owner','howdy@kanabsports.com',?,datetime('now','+1 hour'))").run(hash);
const payload={rows,evidence:'School-authorized synthetic test',confirmed:true};
assert.equal((await call(roster,'/api/guardian-import',payload)).status,401);
assert.equal((await call(roster,'/api/guardian-import',{...payload,rows:[...rows,{...rows[0],email:'second@example.test',team_code:'KS-MISSING'}]},'ks_admin=owner-token')).status,400);
assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM guardian_memberships').get().n,0);
let r=await call(roster,'/api/guardian-import',payload,'ks_admin=owner-token');assert.equal(r.status,200);assert.equal((await r.json()).imported,1);
r=await call(roster,'/api/guardian-import',payload,'ks_admin=owner-token');assert.equal((await r.json()).skipped,1);
sqlite.prepare("UPDATE guardian_memberships SET status='revoked'").run();
assert.equal((await call(roster,'/api/guardian-import',payload,'ks_admin=owner-token')).status,409);
console.log('PASS: CSV validation, owner-only import, all-or-nothing validation, duplicate skip, revoked-access protection.');
const savedFetch=globalThis.fetch;let code;
try{
 globalThis.fetch=async()=>new Response('{}',{status:503});
 const otp={action:'request_otp',email:'coach@example.test'};
 assert.equal((await call(account,'/api/coach-account',otp)).status,502);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coach_login_otps').get().n,0);
 globalThis.fetch=async(url,init)=>{code=JSON.parse(init.body).text.match(/code is (\d{6})/)[1];return new Response('{}')};
 assert.equal((await call(account,'/api/coach-account',otp)).status,200);
 const password={action:'set_password',email:otp.email,otp:code,password:'test-password-123'};
 r=await call(account,'/api/coach-account',password);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure/);
 assert.equal((await call(account,'/api/coach-account',password)).status,403);
 assert.equal((await call(account,'/api/coach-account',{action:'login',email:otp.email,password:password.password})).status,200);
 await call(account,'/api/coach-account',otp);password.otp=code;
 assert.equal((await call(account,'/api/coach-account',password)).status,200);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coach_sessions').get().n,1,'Reset invalidates old sessions');
 await call(account,'/api/coach-account',otp);await call(account,'/api/coach-account',otp);
 assert.equal((await call(account,'/api/coach-account',otp)).status,429);
 globalThis.fetch=async url=>{assert.match(url,/turnstile/);return Response.json({success:true})};
 const form=new FormData();for(const [k,v] of Object.entries({name:'Coach',email:otp.email,organization:'KHS',team_name:'Test',sport:'Soccer',role:'Coach',phone:'4355550100','cf-turnstile-response':'mock'}))form.set(k,v);
 r=await register({request:new Request('https://kanabsports.com/coach-register',{method:'POST',body:form}),env,waitUntil(){}});
 assert.equal(r.status,409);assert.equal(sqlite.prepare("SELECT status FROM coach_access_requests WHERE id='coach'").get().status,'approved');
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM coach_sessions').get().n,1);
 console.log('PASS: email failure reported; single-use verification code; password setup/login; reset revokes sessions; rate limiting; duplicate signup preserves account. No external messages sent.');
}finally{globalThis.fetch=savedFetch;sqlite.close()}
