import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {removeBullsharksTest} from '../functions/_migrations/remove-bullsharks-test.js';
const sql=new DatabaseSync(':memory:');const db={prepare(q){const st=sql.prepare(q);let args=[];return{bind(...a){args=a;return this},async run(){return st.run(...args)},async first(){return st.get(...args)||null},async all(){return {results:st.all(...args)}}}},async batch(writes){sql.exec('BEGIN');try{const out=[];for(const s of writes)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
sql.exec(`CREATE TABLE coach_access_requests(id TEXT,team_name TEXT,organization TEXT,team_code TEXT,created_at TEXT);
CREATE TABLE coach_documents(id TEXT,verification_id TEXT,team TEXT,created_at TEXT);
CREATE TABLE coach_submissions(id TEXT,accountable_coach_id TEXT,team TEXT,created_at TEXT);
CREATE TABLE coach_score_assistants(id TEXT,coach_id TEXT);
CREATE TABLE coach_sessions(id TEXT,coach_id TEXT);
CREATE TABLE coach_schedule_games(id TEXT,coach_id TEXT,source_document_id TEXT);
CREATE TABLE coach_roster_uploads(document_id TEXT,coach_id TEXT,payload_json TEXT);
CREATE TABLE dev_documents(document_id TEXT,payload_json TEXT);
CREATE TABLE parent_family(email TEXT,team_code TEXT);
CREATE TABLE parent_accounts(email TEXT);
CREATE TABLE guardian_memberships(id TEXT,email TEXT,team_code TEXT);
CREATE TABLE school_approved_memberships(membership_id TEXT);
CREATE TABLE school_teams(team_code TEXT);
CREATE TABLE push_devices(id TEXT,codes TEXT);
CREATE TABLE family_driver_plans(id TEXT,team_code TEXT,provider_id TEXT,status TEXT);
INSERT INTO coach_access_requests VALUES('test','Bullsharks','Travel','TEST','2026-10-08'),('real','Real Team','City','REAL','2026-10-08'),('future','Bullsharks','Another City','FUTURE','2026-10-10');
INSERT INTO coach_documents VALUES('doc','test','Bullsharks','2026-10-08'),('real-doc','real','Real Team','2026-10-08');
INSERT INTO coach_submissions VALUES('score','test','Bullsharks','2026-10-09'),('real-score','real','Real Team','2026-10-09');
INSERT INTO coach_score_assistants VALUES('assistant','test'),('real-assistant','real');
INSERT INTO coach_sessions VALUES('session','test'),('real-session','real');
INSERT INTO coach_schedule_games VALUES('game','test','doc'),('real-game','real','real-doc');
INSERT INTO coach_roster_uploads VALUES('doc','test','fake roster');
INSERT INTO dev_documents VALUES('doc','fake schedule');
INSERT INTO parent_accounts VALUES('shared-parent');
INSERT INTO parent_family VALUES('shared-parent','TEST'),('shared-parent','REAL');
INSERT INTO guardian_memberships VALUES('member','shared-parent','TEST'),('real-member','shared-parent','REAL');
INSERT INTO school_approved_memberships VALUES('member'),('real-member');
INSERT INTO school_teams VALUES('TEST'),('REAL');
INSERT INTO push_devices VALUES('device','["TEST","REAL"]');
INSERT INTO family_driver_plans VALUES('plan','TEST','receipt','scheduled');`);
let cancelled=0;const original=globalThis.fetch;globalThis.fetch=async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails/receipt/cancel');assert.equal(opts.method,'POST');cancelled++;return Response.json({id:'receipt'})};
try{
 const result=await removeBullsharksTest(db,{RESEND_API_KEY:'mock'});assert.equal(result.deleted_rows,13);assert.equal(cancelled,1);
 assert.deepEqual(sql.prepare('SELECT id FROM coach_access_requests ORDER BY id').all().map(r=>r.id),['future','real']);
 assert.equal(sql.prepare('SELECT id FROM coach_submissions').get().id,'real-score');
 assert.equal(sql.prepare('SELECT count(*) n FROM coach_roster_uploads').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM dev_documents').get().n,0);
 assert.equal(sql.prepare('SELECT count(*) n FROM parent_accounts').get().n,1);assert.equal(sql.prepare('SELECT team_code FROM parent_family').get().team_code,'REAL');assert.equal(sql.prepare('SELECT codes FROM push_devices').get().codes,'["REAL"]');
 assert.equal(sql.prepare('SELECT membership_id FROM school_approved_memberships').get().membership_id,'real-member');
 assert.equal((await removeBullsharksTest(db,{})).deleted_rows,result.deleted_rows);assert.equal(cancelled,1);
 console.log('PASS: one-time cutoff cleanup removes test scores, roster, schedule, invitations, sessions, team memberships and queued reminders; preserves real teams, parent accounts, other push codes and future same-name teams.');
}finally{globalThis.fetch=original;sql.close()}
