import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {ensureCoachCore,sha256} from '../functions/_lib/coach-auth.js';
import {accessSchema,hasMembership} from '../functions/_lib/parent-access.js';
import {schoolSchema,schoolRoles,messagingGate} from '../functions/_lib/school-access.js';
import {authenticate} from '../functions/api/admin-dashboard.js';
import {onRequest as setup} from '../functions/api/school-admin.js';
import {onRequest as roster} from '../functions/api/school-roster.js';
import {onRequest as contacts} from '../functions/api/school-contacts.js';
import {onRequest as auth} from '../functions/api/school-auth.js';
import {onRequest as notices} from '../functions/api/school-parent-notices.js';
import {onRequest as messages} from '../functions/api/coach-messages.js';
import {onRequestPost as ownerImport} from '../functions/api/guardian-import.js';
import {parseCSV,validateStudents,csvText} from '../assets/school-roster.mjs';
const sqlite=new DatabaseSync(':memory:');
const db={prepare(sql){const stmt=sqlite.prepare(sql);let args=[];return {bind(...v){args=v;return this},async run(){const r=stmt.run(...args);return {...r,meta:{changes:Number(r.changes)}}},async first(){return stmt.get(...args)||null},async all(){return {results:stmt.all(...args)}}}},async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const env={SPORTS_DB:db,RESEND_API_KEY:'mock'};
const req=(path,body,cookie='')=>new Request('https://kanabsports.com'+path,{method:body?'POST':'GET',headers:{origin:'https://kanabsports.com','content-type':'application/json',cookie},...(body?{body:JSON.stringify(body)}:{})});
const call=(fn,path,body,cookie)=>fn({request:req(path,body,cookie),env});
await ensureCoachCore(db);await schoolSchema(db);await accessSchema(db);await authenticate(req('/'),db);
sqlite.prepare("INSERT INTO admin_sessions(id,email,token_hash,expires_at) VALUES('owner','howdy@kanabsports.com',?,datetime('now','+1 hour'))").run(await sha256('owner'));
const owner='ks_admin=owner',expiry=new Date(Date.now()+100*86400000).toISOString().slice(0,10),principalExpiry=new Date(Date.now()+200*86400000).toISOString().slice(0,10),year='2026-2027';
let r=await call(setup,'/api/school-admin',{action:'create_school',name:'Test School',email:'principal@example.test',expires:principalExpiry,evidence:'Verified synthetic school authority',confirmed:true},owner);assert.equal(r.status,200);const school=(await r.json()).id;
const school2='other-school';sqlite.prepare('INSERT INTO school_orgs VALUES(?,?,?)').run(school2,'Other School',Date.now());
for(const [id,code,sport] of [['c1','KS-ONE','Soccer'],['c2','KS-TWO','Basketball'],['c3','KS-THREE','Swimming']]){sqlite.prepare("INSERT INTO coach_access_requests(id,name,email,organization,team_name,sport,role,status,team_code) VALUES(?,?,?,'School','Team',?,'Head Coach','approved',?)").run(id,'Coach',id+'@example.test',sport,code);sqlite.prepare("INSERT INTO coach_sessions(id,coach_id,email,token_hash,expires_at) VALUES(?,?,?,?,datetime('now','+1 hour'))").run(id,id,id+'@example.test',await sha256(id));r=await call(setup,'/api/school-admin',{action:'assign_team',team_code:code,kind:'school',school_id:school,evidence:'Verified test school team',confirmed:true},owner);assert.equal(r.status,200)}
const coach='ks_coach=c1';
const ptoken='a'.repeat(64),dtoken='b'.repeat(64);sqlite.prepare('INSERT INTO school_sessions VALUES(?,?,?)').run(await sha256(ptoken),'principal@example.test',Date.now()+3600000);sqlite.prepare('INSERT INTO school_sessions VALUES(?,?,?)').run(await sha256(dtoken),'ad@example.test',Date.now()+3600000);
const principal='__Host-pep_school='+ptoken,delegate='__Host-pep_school='+dtoken,path='/api/school-contacts?school_id='+school;
const studentRows=[{student_ref:'student-1',student_name:'Test Student'}];
assert.deepEqual(validateStudents(parseCSV(csvText(['student_ref','student_name'],studentRows),['student_ref','student_name'])),studentRows);
assert.throws(()=>csvText(['student_ref'],[{student_ref:'=HYPERLINK("bad")'}]));
assert.equal((await call(contacts,path,null,delegate)).status,403);
assert.equal((await call(contacts,'/api/school-contacts?school_id='+school2,null,principal)).status,403);
assert.equal((await call(messages,'/api/coach-messages',{action:'post',body:'Test announcement'},coach)).status,403);
const rosterBody={rows:studentRows,season:'Fall',school_year:year,expires:expiry,confirmed:true,revision:0};
assert.equal((await call(roster,'/api/school-roster',rosterBody,coach)).status,200);
assert.equal((await messagingGate(db,'KS-ONE')).allowed,false);
const contactRows=[{email:'parent@example.test',student_ref:'student-1',team_code:'KS-ONE',season:'Fall',expires:expiry}];
const approval={action:'approve_contacts',team_code:'KS-ONE',revision:1,rows:contactRows,evidence:'Reviewed school-authorized contacts',confirmed:true};
assert.equal((await call(contacts,path,approval,coach)).status,401);
assert.equal((await call(ownerImport,'/api/guardian-import',{rows:contactRows,evidence:'Owner test authorization',confirmed:true},owner)).status,403);
r=await call(contacts,path,{action:'delegate',email:'ad@example.test',expires:expiry,evidence:'Principal appointed athletic director',confirmed:true},principal);assert.equal(r.status,200);
assert.equal((await schoolRoles(db,'ad@example.test',school)).length,1);
assert.equal((await call(contacts,path,{action:'delegate',email:'other@example.test'},delegate)).status,403);
assert.equal((await call(contacts,path,approval,delegate)).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-ONE'),true);
assert.equal(await hasMembership(db,'stranger@example.test','KS-ONE'),false);
assert.equal((await call(messages,'/api/coach-messages',{action:'post',body:'Test announcement'},coach)).status,200);
assert.equal((await call(roster,'/api/school-roster',{...rosterBody,season:'Winter'},'ks_coach=c2')).status,200);
r=await call(contacts,path+'&team_code=KS-TWO',null,delegate);const pending=await r.json();assert.equal(pending.reusable.length,1);
sqlite.prepare("UPDATE school_teams SET school_year='2025-2026' WHERE team_code='KS-TWO'").run();r=await call(contacts,path+'&team_code=KS-TWO',null,delegate);assert.equal((await r.json()).reusable.length,0,'Other school years do not match');
 sqlite.prepare("UPDATE school_teams SET school_year='2026-2027' WHERE team_code='KS-TWO'").run();
 sqlite.prepare("UPDATE school_rosters SET student_ref='different-id' WHERE team_code='KS-TWO'").run();r=await call(contacts,path+'&team_code=KS-TWO',null,delegate);assert.equal((await r.json()).reusable.length,0,'A matching name alone is not enough');
 sqlite.prepare("UPDATE school_rosters SET student_ref='student-1' WHERE team_code='KS-TWO'").run();
 const reusedRows=pending.reusable.map(({email,student_ref,team_code,season,expires})=>({email,student_ref,team_code,season,expires}));
const reuseApproval={...approval,team_code:'KS-TWO',rows:reusedRows,reuse:true};
assert.equal((await call(contacts,path,reuseApproval,delegate)).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-TWO'),true);
assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM parent_family').get().n,1);
assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM school_parent_notices').get().n,1);
const parentToken='c'.repeat(64);sqlite.prepare('INSERT INTO parent_sessions VALUES(?,?,?)').run(await sha256(parentToken),'parent@example.test',Date.now()+3600000);const parent='__Host-ks_parent='+parentToken;
r=await call(notices,'/api/school-parent-notices',null,parent);const notice=(await r.json()).notices[0];assert.equal(notice.old_sport,'Soccer');assert.equal(notice.new_sport,'Basketball');
assert.equal((await call(notices,'/api/school-parent-notices',{action:'opt_out',id:notice.id},principal)).status,401);
assert.equal((await call(notices,'/api/school-parent-notices',{action:'opt_out',id:notice.id},parent)).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-TWO'),false);assert.equal(await hasMembership(db,'parent@example.test','KS-ONE'),true);
assert.equal((await call(contacts,path,{...reuseApproval,reuse:false},delegate)).status,409,'Import cannot override opt-out');
assert.equal((await call(roster,'/api/school-roster',rosterBody,'ks_coach=c3')).status,200);
r=await call(contacts,path+'&team_code=KS-THREE',null,delegate);assert.equal((await r.json()).reusable.length,0,'Prior opt-out excludes automatic reuse');
assert.equal((await call(roster,'/api/school-roster',{...rosterBody,revision:1},coach)).status,200);
assert.equal(await hasMembership(db,'parent@example.test','KS-ONE'),false,'New roster pauses old access');
assert.equal((await call(contacts,path,approval,delegate)).status,409,'Stale approval rejected');
const delegated=sqlite.prepare("SELECT id FROM school_staff WHERE email='ad@example.test'").get();assert.equal((await call(contacts,path,{action:'revoke_staff',id:delegated.id},principal)).status,200);
assert.equal((await call(contacts,path,null,delegate)).status,403,'Existing session cannot bypass revocation');
// A full roster uses set-based writes, not one query per student.
 const many=Array.from({length:100},(_,i)=>({student_ref:'bulk-'+i,student_name:'Synthetic '+i}));
 let queries=0;const counted={...db,prepare(sql){queries++;return db.prepare(sql)}};
 r=await roster({request:req('/api/school-roster',{...rosterBody,rows:many,revision:1},'ks_coach=c3'),env:{...env,SPORTS_DB:counted}});assert.equal(r.status,200);assert.ok(queries<=50,'100-student roster fits query budget: '+queries);
 queries=0;
 r=await contacts({request:req(path,{...approval,team_code:'KS-THREE',revision:2,rows:many.map(s=>({email:s.student_ref+'@example.test',student_ref:s.student_ref,team_code:'KS-THREE',season:'Fall',expires:expiry}))},principal),env:{...env,SPORTS_DB:counted}});assert.equal(r.status,200);assert.ok(queries<=50,'100-contact approval fits query budget: '+queries);
 assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM guardian_memberships WHERE team_code='KS-THREE'").get().n,100);
 console.log('PASS: school scoping, principal delegation, coach/owner bypass denied, approval gate, roster replacement, school-year reuse, parent notice, opt-out enforcement and delegate revocation.');
const originalFetch=globalThis.fetch;let code;try{
 globalThis.fetch=async(url,init)=>{code=JSON.parse(init.body).text.match(/code is (\d{6})/)[1];return new Response('{}')};
 assert.equal((await call(auth,'/api/school-auth',{action:'request_code',email:'principal@example.test'})).status,200);
 r=await call(auth,'/api/school-auth',{action:'verify',email:'principal@example.test',code});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);
 assert.equal((await call(auth,'/api/school-auth',{action:'verify',email:'principal@example.test',code})).status,403);
 globalThis.fetch=async()=>new Response('{}',{status:503});assert.equal((await call(auth,'/api/school-auth',{action:'request_code',email:'principal@example.test'})).status,502);
 assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM school_login_codes').get().n,0);
 console.log('PASS: single-use school login, secure session cookie, email failure cleanup. No external messages sent.');
}finally{globalThis.fetch=originalFetch;sqlite.close()}
