const bytes=new TextEncoder();
export const b64=v=>btoa(String.fromCharCode(...new Uint8Array(v))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
export const digest=async v=>b64(await crypto.subtle.digest('SHA-256',bytes.encode(v)));
export async function pushSchema(db){for(const sql of [
 'CREATE TABLE IF NOT EXISTS push_config (id INTEGER PRIMARY KEY CHECK(id=1),value TEXT NOT NULL)',
 'CREATE TABLE IF NOT EXISTS push_devices (id TEXT PRIMARY KEY,endpoint TEXT NOT NULL UNIQUE,token_hash TEXT NOT NULL,codes TEXT NOT NULL,updated INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS push_attempts (message_id TEXT NOT NULL,device_id TEXT NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(message_id,device_id))',
 'CREATE TABLE IF NOT EXISTS push_limits (key TEXT PRIMARY KEY,count INTEGER NOT NULL)'
])await db.prepare(sql).run();}
export async function keys(db){let row=await db.prepare('SELECT value FROM push_config WHERE id=1').first();if(!row){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const value=JSON.stringify({publicKey:b64(await crypto.subtle.exportKey('raw',pair.publicKey)),privateKey:await crypto.subtle.exportKey('jwk',pair.privateKey)});await db.prepare('INSERT OR IGNORE INTO push_config(id,value) VALUES(1,?)').bind(value).run();row=await db.prepare('SELECT value FROM push_config WHERE id=1').first();}return JSON.parse(row.value);}
export function validEndpoint(value){try{const u=new URL(value);return value.length<2048&&u.protocol==='https:'&&!u.port&&!u.username&&!u.password&&!u.hash&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.services.mozilla.com')||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.push.apple.com'))&&u.pathname.length>1;}catch{return false;}}
export async function sendPush(db,device){if(!validEndpoint(device.endpoint))return 'invalid';const key=await keys(db),header=b64(bytes.encode(JSON.stringify({typ:'JWT',alg:'ES256'}))),claims=b64(bytes.encode(JSON.stringify({aud:new URL(device.endpoint).origin,exp:Math.floor(Date.now()/1000)+3600,sub:'mailto:howdy@kanabsports.com'}))),input=header+'.'+claims;const privateKey=await crypto.subtle.importKey('jwk',key.privateKey,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const signature=b64(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},privateKey,bytes.encode(input)));
 // No payload: notification text is generic and provided by our service worker.
 const response=await fetch(device.endpoint,{method:'POST',headers:{Authorization:`vapid t=${input}.${signature}, k=${key.publicKey}`,TTL:'3600',Urgency:'normal'},redirect:'error',signal:AbortSignal.timeout(10000)});
 if([404,410].includes(response.status)){await db.prepare('DELETE FROM push_devices WHERE id=?').bind(device.id).run();return 'expired';}return response.ok?'accepted':'rejected';}
export async function notifyTeam(db,code,messageId){await pushSchema(db);const rows=(await db.prepare('SELECT id,endpoint,codes FROM push_devices').all()).results||[];const totals={accepted:0,failed:0};for(const device of rows){if(!JSON.parse(device.codes).includes(code))continue;const claim=await db.prepare("INSERT OR IGNORE INTO push_attempts(message_id,device_id,status,created) VALUES(?,?,'sending',?) RETURNING device_id").bind(messageId,device.id,Date.now()).first();if(!claim)continue;let status='unknown';try{status=await sendPush(db,device);}catch{}await db.prepare('UPDATE push_attempts SET status=? WHERE message_id=? AND device_id=?').bind(status,messageId,device.id).run();totals[status==='accepted'?'accepted':'failed']++;}return totals;}
