// Sterling contributor login: simple password verification with a signed 24-hour cookie.
const SESSION_SECONDS=24*60*60;
const PASSWORD_SHA256='2ac025b0e97449a98fd0990de01604eac36abfad0e9c71e4088bfee812be6ddc';
const SIGNING_FALLBACK='ks-sterling-session-v1';
export async function onRequestGet({request,env}){return json({authenticated:Boolean(await authenticate(request,signingSecret(env)))})}
export async function onRequestPost({request,env}){try{const form=await request.formData(),action=String(form.get('action')||'').trim();if(action==='logout')return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':'ks_sterling=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0','Cache-Control':'no-store'}});if(String(form.get('website')||'').trim())return json({success:true});const password=String(form.get('password')||'');if(!password)return json({success:false,error:'Enter the shared password.'},400);const attempted=await sha256(password);if(!constantTimeEqual(attempted,PASSWORD_SHA256))return json({success:false,error:'That password does not match.'},403);const token=await createSession(signingSecret(env));return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':`ks_sterling=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_SECONDS}`,'Cache-Control':'no-store'}})}catch(error){console.error('sterling auth error',error);return json({success:false,error:'Unable to sign in right now.'},500)}}
function signingSecret(env){return env?.RESEND_API_KEY||env?.TURNSTILE_SECRET_KEY||SIGNING_FALLBACK}
export async function authenticate(request,secret){const cookie=request.headers.get('Cookie')||'',match=cookie.match(/(?:^|;\s*)ks_sterling=([^;]+)/);if(!match)return false;try{const token=decodeURIComponent(match[1]),dot=token.lastIndexOf('.');if(dot<1)return false;const payload=token.slice(0,dot),signature=token.slice(dot+1),expected=await hmac(secret,payload);if(!constantTimeEqual(signature,expected))return false;const data=JSON.parse(new TextDecoder().decode(fromBase64Url(payload)));return Number(data.exp)>Date.now()}catch{return false}}
async function createSession(secret){const payload=toBase64Url(new TextEncoder().encode(JSON.stringify({exp:Date.now()+SESSION_SECONDS*1000})));return payload+'.'+await hmac(secret,payload)}
async function sha256(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('')}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return toBase64Url(new Uint8Array(bytes))}
function toBase64Url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function fromBase64Url(value){const s=value.replaceAll('-','+').replaceAll('_','/'),padded=s+'='.repeat((4-s.length%4)%4),raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function constantTimeEqual(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
