const SESSION_SECONDS=24*60*60,ITERATIONS=150000,SALT='25952c12d6d669ba8ed8ea5eefe48969',PASSWORD_HASH='93ce24282299a355d5b986e0daa5abf8cfafe33340d88d3c4265cb17a560f519';
export async function onRequestGet({request,env}){return json({authenticated:Boolean(await authenticate(request,env.TURNSTILE_SECRET_KEY))})}
export async function onRequestPost({request,env}){try{const form=await request.formData(),action=clean(form.get('action'),30);if(action==='logout')return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':'ks_sterling=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0','Cache-Control':'no-store'}});if(clean(form.get('website'),100))return json({success:true});const password=String(form.get('password')||''),turnstile=clean(form.get('cf-turnstile-response'),3000);if(!password)return json({success:false,error:'Enter the shared password.'},400);if(!turnstile||!env.TURNSTILE_SECRET_KEY)return json({success:false,error:'Please wait for verification to finish.'},400);if(!await verifyTurnstile(request,env.TURNSTILE_SECRET_KEY,turnstile))return json({success:false,error:'Human verification failed. Refresh and try again.'},403);const attempted=await passwordHash(password,SALT,ITERATIONS);if(!constantTimeEqual(attempted,PASSWORD_HASH))return json({success:false,error:'That password does not match.'},403);const token=await createSession(env.TURNSTILE_SECRET_KEY);return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':`ks_sterling=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${SESSION_SECONDS}`,'Cache-Control':'no-store'}})}catch(error){console.error('sterling auth error',error);return json({success:false,error:'Unable to sign in right now.'},500)}}
export async function authenticate(request,secret){if(!secret)return false;const cookie=request.headers.get('Cookie')||'',match=cookie.match(/(?:^|;\s*)ks_sterling=([^;]+)/);if(!match)return false;try{const token=decodeURIComponent(match[1]),[payload,signature]=token.split('.');if(!payload||!signature)return false;const expected=await hmac(secret,payload);if(!constantTimeEqual(signature,expected))return false;const data=JSON.parse(new TextDecoder().decode(fromBase64Url(payload)));return Number(data.exp)>Date.now()}catch{return false}}
async function createSession(secret){const payload=toBase64Url(new TextEncoder().encode(JSON.stringify({exp:Date.now()+SESSION_SECONDS*1000})));return payload+'.'+await hmac(secret,payload)}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return toBase64Url(new Uint8Array(bytes))}
function toBase64Url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function fromBase64Url(value){const s=value.replaceAll('-','+').replaceAll('_','/'),padded=s+'='.repeat((4-s.length%4)%4),raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function verifyTurnstile(request,secret,response){const body=new URLSearchParams({secret,response}),ip=request.headers.get('CF-Connecting-IP');if(ip)body.set('remoteip',ip);const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});return r.ok&&Boolean((await r.json()).success)}
async function passwordHash(password,saltHex,iterations){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),salt=new Uint8Array(saltHex.match(/.{2}/g).map(x=>parseInt(x,16))),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('')}
function constantTimeEqual(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function clean(v,max=500){return String(v||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,max)}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
