const SESSION_SECONDS=24*60*60,ITERATIONS=150000,SALT='25952c12d6d669ba8ed8ea5eefe48969',PASSWORD_HASH='93ce24282299a355d5b986e0daa5abf8cfafe33340d88d3c4265cb17a560f519';
export async function onRequestGet({request,env}){if(!env.SPORTS_DB)return json({authenticated:false});await schema(env.SPORTS_DB);return json({authenticated:Boolean(await authenticate(request,env.SPORTS_DB))})}
export async function onRequestPost({request,env}){if(!env.SPORTS_DB)return json({success:false,error:'Access is unavailable.'},503);try{const form=await request.formData(),action=clean(form.get('action'),30);if(action==='logout')return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':'ks_sterling=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0','Cache-Control':'no-store'}});if(clean(form.get('website'),100))return json({success:true});const password=String(form.get('password')||''),turnstile=clean(form.get('cf-turnstile-response'),3000);if(!password)return json({success:false,error:'Enter the shared password.'},400);if(!turnstile||!env.TURNSTILE_SECRET_KEY)return json({success:false,error:'Please wait for verification to finish.'},400);if(!await verifyTurnstile(request,env.TURNSTILE_SECRET_KEY,turnstile))return json({success:false,error:'Human verification failed. Refresh and try again.'},403);const attempted=await passwordHash(password,SALT,ITERATIONS);if(!constantTimeEqual(attempted,PASSWORD_HASH))return json({success:false,error:'That password does not match.'},403);await schema(env.SPORTS_DB);const token=randomToken(),hash=await sha256(token),expires=new Date(Date.now()+SESSION_SECONDS*1000).toISOString();await env.SPORTS_DB.prepare(`DELETE FROM sterling_sessions WHERE datetime(expires_at)<=datetime('now')`).run();await env.SPORTS_DB.prepare(`INSERT INTO sterling_sessions (id,token_hash,expires_at,created_at) VALUES (?,?,?,datetime('now'))`).bind(crypto.randomUUID(),hash,expires).run();return new Response(JSON.stringify({success:true}),{headers:{'Content-Type':'application/json','Set-Cookie':`ks_sterling=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${SESSION_SECONDS}`,'Cache-Control':'no-store'}})}catch(error){console.error('sterling auth error',error);return json({success:false,error:'Unable to sign in right now.'},500)}}
export async function authenticate(request,db){await schema(db);const cookie=request.headers.get('Cookie')||'',match=cookie.match(/(?:^|;\s*)ks_sterling=([^;]+)/);if(!match)return null;const hash=await sha256(decodeURIComponent(match[1]));return db.prepare(`SELECT id FROM sterling_sessions WHERE token_hash=? AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(hash).first()}
async function schema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS sterling_sessions (id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function verifyTurnstile(request,secret,response){const body=new URLSearchParams({secret,response}),ip=request.headers.get('CF-Connecting-IP');if(ip)body.set('remoteip',ip);const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});return r.ok&&Boolean((await r.json()).success)}
function randomToken(){const b=crypto.getRandomValues(new Uint8Array(32));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
async function passwordHash(password,saltHex,iterations){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),salt=new Uint8Array(saltHex.match(/.{2}/g).map(x=>parseInt(x,16))),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('')}
function constantTimeEqual(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function clean(v,max=500){return String(v||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,max)}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
