const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const role=params.get('role')==='coach'?'coach':'parent';
let current=params.get('conversation')||'',older=null,choices=[],pending=null,busy=false,loaded=false;
$('messageTopic').hidden=role!=='coach';$('subject').required=role==='coach';
$(role+'Link').setAttribute('aria-current','page');$('signIn').href=role==='coach'?'/coach-account.html':'/family/';
async function api(path,body){
 const [endpoint,...query]=path.split('&');
 const r=await fetch('/api/'+endpoint+'?role='+role+(query.length?'&'+query.join('&'):''),{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const d=await r.json();
 if(!r.ok){if(r.status===401){$('login').hidden=false;$('app').hidden=true;}if(r.status===401||r.status===404){$('history').replaceChildren();$('compose').hidden=true;}throw Error(d.error||'Request failed.');}return d;
}
const status=text=>$('status').textContent=text;
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function error(e){status(e.message);}
async function inbox(){const d=await api('private-messages');$('login').hidden=true;$('app').hidden=false;loaded=true;choices=d.choices;$('startPanel').hidden=role!=='parent';$('coach').replaceChildren(...choices.map((c,i)=>{const o=node('option',c.team+' · '+c.coach);o.value=i;return o;}));$('start').disabled=!choices.length;$('threads').replaceChildren();if(!d.conversations.length)$('threads').append(node('p','No conversations yet.','hint'));for(const c of d.conversations){const b=node('button',c.name+' · '+c.team,'thread');if(c.id===current)b.setAttribute('aria-current','true');b.onclick=()=>select(c.id).catch(error);$('threads').append(b);}status('Signed in as '+d.actor.name+' · '+role+' inbox');}
function render(messages,prepend=false){const fragment=document.createDocumentFragment();for(const m of messages){const article=node('article','','bubble'+(m.sender_role===role?' mine':''));article.append(node('strong',m.sender_name+' · '+m.sender_role),node('p',(m.subject?m.subject+' · ':'')+(m.category||'general'),'hint'),node('p',m.body),node('small',new Date(m.created).toLocaleString()));if(m.sender_role===role)article.append(node('p',`Saved in Pep · Email: ${m.email_status||'pending'} · Push: ${m.push_status||'pending'}${m.notification_status==='unconfirmed'||m.notification_status==='processing'?' · Notification completion unconfirmed':''}`,'hint'));fragment.append(article);}if(prepend)$('history').prepend(fragment);else $('history').replaceChildren(fragment);}
async function history(before){const requested=current;const d=await api('private-messages&conversation='+encodeURIComponent(current)+(before?'&before='+before:''));if(requested!==current)return;$('conversationTitle').textContent=d.conversation.team+' · '+d.conversation.coach;render(d.messages,!!before);older=d.older;$('older').hidden=!older;$('compose').hidden=false;if(!before)$('history').scrollTop=$('history').scrollHeight;}
async function select(id){if(busy)return;if($('message').value&&id!==current&&!confirm('Discard this unsent draft?'))return;current=id;pending=null;$('message').value='';$('compose').hidden=true;$('history').replaceChildren();window.history.replaceState(null,'','?role='+role+'&conversation='+encodeURIComponent(id));await history();await inbox();}
$('start').onclick=async()=>{try{const c=choices[Number($('coach').value)];if(!c)return;const d=await api('private-messages',{action:'start',...c});await select(d.id);}catch(e){error(e);}};
$('compose').onsubmit=async e=>{e.preventDefault();if(busy)return;const message=$('message').value.trim();if(!message)return;if(!pending||pending.message!==message||pending.conversation!==current||pending.category!==$('category').value||pending.subject!==$('subject').value.trim())pending={action:'send',message,message_id:crypto.randomUUID(),conversation:current,category:role==='coach'?$('category').value:'general',subject:role==='coach'?$('subject').value.trim():''};busy=true;$('send').disabled=true;try{await api('private-messages',pending);pending=null;$('message').value='';await history();status('Message saved in Pep. Notification status updates when you refresh.');}catch(e){error(e);}finally{busy=false;$('send').disabled=false;}};
$('older').onclick=()=>history(older).catch(error);$('refresh').onclick=()=>refresh().catch(error);$('signedIn').onclick=()=>location.reload();
async function refresh(){await inbox();if(current)await history();}
// No background refresh while a draft is being composed; never store messages locally.
setInterval(()=>{if(loaded&&!document.hidden&&!busy&&!$('message').value)refresh().catch(error);},30000);
async function pushSetup(){if(!('serviceWorker' in navigator)||!('PushManager' in window))throw Error('Push is unavailable in this browser. On iPhone, add this page to your Home Screen and open it there.');const reg=await navigator.serviceWorker.register('/messages/sw.js',{scope:'/messages/'});if(!reg.active)await new Promise(resolve=>{const worker=reg.installing||reg.waiting;if(!worker)return resolve();worker.addEventListener('statechange',()=>{if(worker.state==='activated')resolve();});});return reg;}
function token(){let t=localStorage.getItem('pep-private-push-token');if(!t){t=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem('pep-private-push-token',t);}return t;}
async function push(action){try{const reg=await pushSetup();let sub=await reg.pushManager.getSubscription();if(action==='subscribe'){if(await Notification.requestPermission()!=='granted')throw Error('Notification permission was not granted.');const d=await api('private-message-push'),str=d.publicKey.replace(/-/g,'+').replace(/_/g,'/');sub=sub||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(str+'='.repeat((4-str.length%4)%4)),c=>c.charCodeAt(0))});}if(!sub)throw Error('Enable push notifications first.');const d=await api('private-message-push',{action,endpoint:sub.endpoint,token:token()});if(action==='unsubscribe')await sub.unsubscribe();$('pushStatus').textContent=action==='test'?'Test provider status: '+d.status+'. Check this device.':action==='subscribe'?'Push enabled for this signed-in account. Send a test to verify.':'Push turned off.';}catch(e){$('pushStatus').textContent=e.message;}}
$('enablePush').onclick=()=>push('subscribe');$('testPush').onclick=()=>push('test');$('disablePush').onclick=()=>push('unsubscribe');
refresh().catch(error);

async function loadPreferences(){try{const d=await api('notification-preferences');const table=document.createElement('table');const header=document.createElement('tr');for(const label of ['Topic','Mute email','Mute push'])header.append(node('th',label));table.append(header);for(const p of d.preferences){const row=document.createElement('tr');row.append(node('td',p.category));for(const channel of ['email','push']){const cell=document.createElement('td'),input=document.createElement('input');input.type='checkbox';input.dataset.category=p.category;input.dataset.channel=channel;input.checked=!!p[channel+'_muted'];input.setAttribute('aria-label','Mute '+channel+' for '+p.category);cell.append(input);row.append(cell);}table.append(row);}$('preferenceMatrix').replaceChildren(table);}catch(e){error(e);}}
$('savePreferences').onclick=async()=>{try{const preferences=['general','schedule','logistics','stats','urgent'].map(category=>({category,email_muted:document.querySelector(`[data-category="${category}"][data-channel="email"]`).checked,push_muted:document.querySelector(`[data-category="${category}"][data-channel="push"]`).checked}));await api('notification-preferences',{preferences});status('Notification preferences saved.');}catch(e){error(e);}};loadPreferences();
