const $=id=>document.getElementById(id),token=new URLSearchParams(location.hash.slice(1)).get('invite');
const el=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function api(body){const r=await fetch('/api/family-sharing',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok){if(r.status===401)$('login').hidden=false;throw Error(d.error||'Request failed.');}return d;}
function error(e){$('status').textContent=e.message;}
async function act(body){const d=await api(body);$('status').textContent=d.message||'Saved.';await load();return d;}
async function load(){const d=await api();$('login').hidden=true;$('controls').hidden=false;$('accept').hidden=!token;$('sender').value=d.sender_email;$('teams').replaceChildren();for(const code of d.teams){const label=el('label',code+' '),box=document.createElement('input');box.type='checkbox';box.value=code;box.name='team';label.prepend(box);$('teams').append(label,document.createElement('br'));}$('grants').replaceChildren();for(const g of d.grants){const row=el('article',g.recipient_email+' · '+g.status);for(const [key,title] of [['can_edit','Can edit driver plans'],['is_driver','Driver']]){const label=el('label',title),box=document.createElement('input');box.type='checkbox';box.checked=!!g[key];box.onchange=()=>act({action:'permissions',id:g.id,can_edit:key==='can_edit'?box.checked:!!g.can_edit,is_driver:key==='is_driver'?box.checked:!!g.is_driver}).catch(error);label.prepend(box);row.append(label);}const revoke=el('button','Remove access');revoke.onclick=()=>act({action:'revoke',id:g.id}).catch(error);row.append(revoke);$('grants').append(row);}$('invites').replaceChildren();for(const i of d.invites){const row=el('p',i.recipient_email+' · '+i.status+' · '+(i.delivery||'not sent'));if(i.status==='requested'){const approve=el('button','Choose access and invite');approve.onclick=()=>{$('recipient').value=i.recipient_email;$('recipient').focus();};row.append(approve);}if(['pending','requested'].includes(i.status)){const cancel=el('button','Cancel');cancel.onclick=()=>act({action:'cancel_invite',id:i.id}).catch(error);row.append(cancel);}$('invites').append(row);}$('shared').replaceChildren();for(const s of d.schedules){const row=el('article',s.owner_name+' · '+s.name+' · '+(s.can_edit?'May edit driver plans':'View only')+(s.is_driver?' · Driver':''));for(const e of s.events)row.append(el('p',e.date+' · '+e.time+' · '+e.title+(e.cancelled?' · CANCELLED':'')));$('shared').append(row);}}
$('continue').onclick=()=>load().catch(error);
$('acceptInvite').onclick=async()=>{try{await act({action:'accept',token});history.replaceState(null,'',location.pathname);location.href='/family/?shared=1';}catch(e){error(e);}};
$('inviteForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const d=await act({action:'invite',recipient_email:$('recipient').value,team_codes:[...document.querySelectorAll('[name=team]:checked')].map(x=>x.value),can_edit:$('canEdit').checked,is_driver:$('isDriver').checked});$('status').textContent='Invitation accepted by email provider. Inbox receipt is not yet confirmed.';}catch(e){error(e);}finally{button.disabled=false;}};
$('rotate').onclick=async()=>{try{const d=await act({action:'rotate_code'});$('code').textContent=d.code;}catch(e){error(e);}};
$('requestForm').onsubmit=e=>{e.preventDefault();act({action:'request_code',code:$('requestCode').value}).catch(error);};
load().catch(error);
